import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const supabaseUrl=Deno.env.get("SUPABASE_URL")!;const serviceRole=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const admin=createClient(supabaseUrl,serviceRole,{auth:{persistSession:false}});const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});
async function sha256Hex(input:string){const buf=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(input));return Array.from(new Uint8Array(buf)).map(b=>b.toString(16).padStart(2,"0")).join("")}
async function authenticate(req:Request){const deviceId=req.headers.get("x-device-id")||"",token=req.headers.get("x-device-token")||"";if(!deviceId||token.length<24)return null;const tokenHash=await sha256Hex(token);const{data,error}=await admin.from("devices").select("id,owner_id,name").eq("id",deviceId).eq("token_hash",tokenHash).maybeSingle();return error||!data?null:data}
serve(async req=>{try{const device=await authenticate(req);if(!device)return json({error:"unauthorized"},401);const action=new URL(req.url).searchParams.get("action")||"";
if(req.method==="POST"&&action==="heartbeat"){const body=await req.json(),metrics=body.metrics||{},now=new Date().toISOString();const{error:e1}=await admin.from("devices").update({name:body.device_name||device.name,agent_version:body.agent_version||null,windows_version:body.windows_version||null,last_seen:now,status:"ONLINE"}).eq("id",device.id);if(e1)throw e1;const{error:e2}=await admin.from("device_status").upsert({device_id:device.id,...metrics,shutdown_due_at:body.shutdown_due_at||null,shutdown_action:body.shutdown_action||null,updated_at:now});if(e2)throw e2;return json({ok:true,server_time:now})}
if(req.method==="GET"&&action==="commands"){const now=new Date().toISOString();await admin.from("device_commands").update({status:"EXPIRED"}).eq("device_id",device.id).eq("status","PENDING").lt("expires_at",now);const{data,error}=await admin.from("device_commands").select("id,command,parameters,created_at,expires_at").eq("device_id",device.id).eq("status","PENDING").gt("expires_at",now).order("created_at",{ascending:true}).limit(5);if(error)throw error;const ids=(data||[]).map(x=>x.id);if(ids.length)await admin.from("device_commands").update({status:"RECEIVED",received_at:now}).in("id",ids).eq("status","PENDING");return json({commands:data||[]})}
if(req.method==="POST"&&action==="result"){const body=await req.json();if(!body.command_id||!["SUCCESS","FAILED","REJECTED"].includes(body.status))return json({error:"invalid result"},400);const{data:cmd}=await admin.from("device_commands").select("id,command").eq("id",body.command_id).eq("device_id",device.id).maybeSingle();if(!cmd)return json({error:"command not found"},404);const now=new Date().toISOString();const{error}=await admin.from("device_commands").update({status:body.status,executed_at:now,result:body.result||{},error_message:body.error_message||null}).eq("id",cmd.id);if(error)throw error;if(body.result&&(Object.prototype.hasOwnProperty.call(body.result,"shutdown_due_at")||Object.prototype.hasOwnProperty.call(body.result,"shutdown_action")))await admin.from("device_status").update({shutdown_due_at:body.result.shutdown_due_at??null,shutdown_action:body.result.shutdown_action??null,updated_at:now}).eq("device_id",device.id);await admin.from("device_events").insert({device_id:device.id,user_id:null,event_type:"COMMAND_RESULT",message:`${cmd.command}: ${body.status}`,result:body.error_message||body.result?.message||body.status});return json({ok:true})}
return json({error:"not found"},404)}catch(err){console.error(err);return json({error:"internal_error"},500)}});
