import { createClient } from 'npm:@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-mms-session,apikey,authorization','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json; charset=utf-8'};
const URL=Deno.env.get('SUPABASE_URL')!,SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}}),enc=new TextEncoder();
const out=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:cors}),hex=(b:Uint8Array)=>[...b].map(x=>x.toString(16).padStart(2,'0')).join('');
async function sha256(s:string){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s))))}
async function admin(req:Request,body:any){const raw=req.headers.get('x-mms-session')||body?.session||'';if(!raw)throw new Error('UNAUTHORIZED');const h=await sha256(raw);const{data:s}=await db.from('mms_sessions').select('user_id,expires_at').eq('token_hash',h).gt('expires_at',new Date().toISOString()).maybeSingle();if(!s)throw new Error('UNAUTHORIZED');const{data:u}=await db.from('mms_users').select('id,display_name,role,active').eq('id',s.user_id).maybeSingle();if(!u?.active)throw new Error('UNAUTHORIZED');if(u.role!=='admin')throw new Error('FORBIDDEN');return u}
function cleanEmail(v:any){const e=String(v||'').trim().toLowerCase();if(!e)return null;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e))throw new Error('INVALID_EMAIL');return e.slice(0,320)}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const body=await req.json().catch(()=>({})),action=String(body.action||'admin-users');await admin(req,body);
if(action==='admin-users'){const{data,error}=await db.from('mms_users').select('id,display_name,role,active,email,email_verified,identity_provider,external_subject,last_login_at,created_at,updated_at').order('display_name');if(error)throw error;return out({ok:true,users:data||[]})}
if(action==='admin-save-identity'){const id=String(body.user_id||''),email=cleanEmail(body.email),provider=['local_pin','email_pin','google'].includes(String(body.identity_provider))?String(body.identity_provider):'local_pin',verified=!!body.email_verified;if(!id)return out({ok:false,error:'USER_REQUIRED'},400);if(!email&&verified)return out({ok:false,error:'EMAIL_REQUIRED_FOR_VERIFICATION'},400);const patch:any={email,email_verified:email?verified:false,identity_provider:provider,updated_at:new Date().toISOString()};const{data,error}=await db.from('mms_users').update(patch).eq('id',id).select('id,email,email_verified,identity_provider').maybeSingle();if(error){if(String(error.code)==='23505')return out({ok:false,error:'EMAIL_EXISTS'},409);throw error}if(!data)return out({ok:false,error:'USER_NOT_FOUND'},404);return out({ok:true,user:data})}
return out({ok:false,error:'Unknown action'},400)}catch(e){const msg=e instanceof Error?e.message:String(e);if(msg==='UNAUTHORIZED')return out({ok:false,error:'กรุณาเข้าสู่ระบบใหม่'},401);if(msg==='FORBIDDEN')return out({ok:false,error:'ไม่มีสิทธิ์ Admin'},403);if(msg==='INVALID_EMAIL')return out({ok:false,error:'รูปแบบอีเมลไม่ถูกต้อง'},400);console.error(e);return out({ok:false,error:'เกิดข้อผิดพลาดของระบบ',detail:msg},500)}});
