import { createClient } from 'npm:@supabase/supabase-js@2';

const cors={
 'Access-Control-Allow-Origin':'*',
 'Access-Control-Allow-Headers':'content-type,x-mms-session,apikey,authorization',
 'Access-Control-Allow-Methods':'POST,OPTIONS',
 'Content-Type':'application/json; charset=utf-8'
};
const URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const db=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}});
const BUCKET='mms-media';
const enc=new TextEncoder();
const out=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:cors});
const hex=(b:Uint8Array)=>[...b].map(x=>x.toString(16).padStart(2,'0')).join('');
async function sha256(s:string){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s))))}
function safeName(s:string){return s.normalize('NFKC').replace(/[\\/:*?"<>|\u0000-\u001f]/g,'_').replace(/\s+/g,' ').trim().slice(0,180)||'file'}
function mediaType(mime:string,name:string){const m=(mime||'').toLowerCase(),n=(name||'').toLowerCase();if(m.startsWith('video/')||/\.(mp4|mov|mkv|avi|mts|m2ts|ts|webm)$/i.test(n))return 'video';if(m.startsWith('audio/')||/\.(mp3|wav|m4a|aac|flac|ogg)$/i.test(n))return 'audio';if(m.startsWith('image/'))return 'image';if(m.includes('pdf')||m.includes('document')||/\.(pdf|docx?|xlsx?|pptx?|txt)$/i.test(n))return 'document';return 'other'}
async function sessionFrom(req:Request,body:any){const raw=req.headers.get('x-mms-session')||body?.session||'';if(!raw)return null;const h=await sha256(raw);const {data:s}=await db.from('mms_sessions').select('id,user_id,expires_at').eq('token_hash',h).gt('expires_at',new Date().toISOString()).maybeSingle();if(!s)return null;const {data:user}=await db.from('mms_users').select('id,display_name,role,active').eq('id',s.user_id).maybeSingle();if(!user?.active)return null;db.from('mms_sessions').update({last_seen_at:new Date().toISOString()}).eq('id',s.id).then(({error})=>{if(error)console.warn('session heartbeat failed',error.message)});return {session:s,user,raw}}
async function requireSession(req:Request,body:any){const c=await sessionFrom(req,body);if(!c)throw new Error('UNAUTHORIZED');return c}
function owned(q:any,ctx:any,column='owner_id'){return ctx.user.role==='admin'?q:q.eq(column,ctx.user.id)}
async function audit(ctx:any,action:string,entity_type:string,entity_id?:string|null,detail:any={},project_id?:string|null,media_file_id?:string|null){await db.from('mms_audit_events').insert({actor_id:ctx.user.id,action,entity_type,entity_id:entity_id||null,detail,project_id:project_id||null,media_file_id:media_file_id||null})}
function bangkokDayStart(){const now=new Date(Date.now()+7*3600000);now.setUTCHours(0,0,0,0);return new Date(now.getTime()-7*3600000).toISOString()}
async function dashboard(ctx:any){const day=bangkokDayStart();
 let qv=db.from('mms_processing_jobs').select('*',{count:'exact',head:true}).eq('module','video').in('status',['queued','processing']);qv=owned(qv,ctx);
 let qc=db.from('mms_cctv_events').select('*',{count:'exact',head:true}).gte('created_at',day);if(ctx.user.role!=='admin'){const {data:ownedMedia}=await db.from('media_files').select('id').eq('owner_id',ctx.user.id);const ids=(ownedMedia||[]).map((x:any)=>x.id);qc=ids.length?qc.in('media_file_id',ids):qc.eq('media_file_id','00000000-0000-0000-0000-000000000000')}
 let qd=db.from('mms_processing_jobs').select('*',{count:'exact',head:true}).eq('module','document').eq('status','completed').gte('completed_at',day);qd=owned(qd,ctx);
 let qm=db.from('media_files').select('*',{count:'exact',head:true}).eq('upload_status','ready');qm=owned(qm,ctx);
 let qj=db.from('mms_processing_jobs').select('*',{count:'exact',head:true}).in('status',['queued','processing']);qj=owned(qj,ctx);
 let qp=db.from('mms_projects').select('*',{count:'exact',head:true}).eq('status','active');qp=owned(qp,ctx);
 const [v,c,d,m,j,p]=await Promise.all([qv,qc,qd,qm,qj,qp]);
 const workerCutoff=new Date(Date.now()-120000).toISOString();const {count:workers}=await db.from('mms_worker_nodes').select('*',{count:'exact',head:true}).gte('last_seen_at',workerCutoff).in('status',['online','busy']);
 return {video_processing:v.count||0,cctv_events:c.count||0,document_today:d.count||0,media_ready:m.count||0,jobs_active:j.count||0,projects_active:p.count||0,workers_online:workers||0,labels:{video:`${v.count||0} งานกำลังประมวลผล`,cctv:`พบ ${c.count||0} เหตุการณ์`,document:`วิเคราะห์วันนี้ ${d.count||0} ไฟล์`,media_library:`${m.count||0} ไฟล์พร้อมใช้`,job_center:`${j.count||0} งานในคิว`,projects:`${p.count||0} โปรเจกต์`}};
}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const body=await req.json().catch(()=>({}));const action=String(body.action||'dashboard');const ctx=await requireSession(req,body);
 if(action==='dashboard')return out({ok:true,stats:await dashboard(ctx)});
 if(action==='library-list'){let q=db.from('media_files').select('id,project_id,media_set_id,segment_index,retention_mode,expires_at,purged_at,purge_reason,released_bytes,original_name,media_type,mime_type,storage_path,size_bytes,sha256,upload_status,source_kind,duration_ms,width,height,fps,codec,timezone,checksum_verified,legal_hold,created_at,updated_at').is('purged_at',null).order('created_at',{ascending:false}).limit(Math.min(Number(body.limit)||100,300));q=owned(q,ctx);const {data,error}=await q;if(error)throw error;const ids=(data||[]).map((x:any)=>x.id);let variants:any[]=[];if(ids.length){const r=await db.from('mms_media_variants').select('*').in('media_file_id',ids);if(r.error)throw r.error;variants=r.data||[]}return out({ok:true,files:data||[],variants});}
 if(action==='library-request-upload'){const name=safeName(String(body.name||''));const mime=String(body.mime_type||'application/octet-stream').slice(0,200);const size=Math.max(0,Number(body.size_bytes)||0);const type=mediaType(mime,name);const projectId=body.project_id?String(body.project_id):null;const sourceKind=['upload','cctv','import','nvr'].includes(String(body.source_kind))?String(body.source_kind):'upload';if(projectId){let pq=db.from('mms_projects').select('id,owner_id').eq('id',projectId);if(ctx.user.role!=='admin')pq=pq.eq('owner_id',ctx.user.id);const {data:p}=await pq.maybeSingle();if(!p)return out({ok:false,error:'ไม่พบ Project หรือไม่มีสิทธิ์'},403)}const id=crypto.randomUUID();const path=`${ctx.user.id}/${new Date().toISOString().slice(0,7)}/${id}/${name}`;const {data:signed,error:se}=await db.storage.from(BUCKET).createSignedUploadUrl(path,{upsert:false});if(se||!signed?.token)throw se||new Error('SIGNED_UPLOAD_FAILED');const {data:file,error}=await db.from('media_files').insert({id,owner_id:ctx.user.id,project_id:projectId,original_name:name,media_type:type,mime_type:mime,storage_path:path,size_bytes:size,upload_status:'uploading',source_kind:sourceKind}).select().single();if(error)throw error;await audit(ctx,'upload_requested','media_file',id,{name,mime,size,sourceKind},projectId,id);return out({ok:true,file,bucket:BUCKET,path,token:signed.token,tus_endpoint:`https://hwzadnpaxiacucvjxmor.storage.supabase.co/storage/v1/upload/resumable`});}
 if(action==='library-complete-upload'){const id=String(body.id||'');let q=db.from('media_files').select('*').eq('id',id);q=owned(q,ctx);const {data:file}=await q.maybeSingle();if(!file)return out({ok:false,error:'ไม่พบไฟล์'},404);const p=String(file.storage_path||'');const cut=p.lastIndexOf('/');const folder=cut>=0?p.slice(0,cut):'';const name=cut>=0?p.slice(cut+1):p;const {data:list,error:le}=await db.storage.from(BUCKET).list(folder,{search:name,limit:20});if(le)throw le;const obj=(list||[]).find((x:any)=>x.name===name);if(!obj)return out({ok:false,error:'ยังตรวจไม่พบไฟล์ที่อัปโหลด',stage:'storage'},409);const objSize=Number(obj?.metadata?.size??obj?.metadata?.contentLength??0),expected=Number(file.size_bytes)||0;if(expected>0&&objSize>0&&Math.abs(objSize-expected)>Math.max(1024,Math.floor(expected*0.01)))return out({ok:false,error:'ขนาดไฟล์ที่อัปโหลดไม่ตรงกับต้นฉบับ กรุณาอัปโหลดใหม่',detail:'storage='+objSize+' expected='+expected,stage:'storage'},409);const patch:any={upload_status:'ready',size_bytes:objSize||expected,updated_at:new Date().toISOString()};if(body.metadata&&typeof body.metadata==='object')patch.metadata=body.metadata;const {data:updated,error}=await db.from('media_files').update(patch).eq('id',id).select().single();if(error)throw error;await db.from('mms_media_variants').upsert({media_file_id:id,variant_type:'original',storage_path:file.storage_path,mime_type:file.mime_type,size_bytes:patch.size_bytes,status:'ready',checksum:patch.sha256||file.sha256},{onConflict:'media_file_id,variant_type'}).then(()=>{}).catch(()=>{});
 if(file.media_type==='video'){const module=file.source_kind==='cctv'?'cctv':'video';await db.from('mms_processing_jobs').insert({owner_id:file.owner_id,project_id:file.project_id,media_file_id:id,module,job_type:'proxy_generate',status:'queued',input:{source_path:file.storage_path,target_height:720,video_codec:'h264',audio_codec:'aac'},idempotency_key:`proxy:${id}:720p`}).then(()=>{}).catch(()=>{});}
 await audit(ctx,'upload_completed','media_file',id,{storage_path:file.storage_path},file.project_id,id);return out({ok:true,file:updated});}
 if(action==='media-download-url'){const id=String(body.id||'');let q=db.from('media_files').select('*').eq('id',id);q=owned(q,ctx);const {data:file}=await q.maybeSingle();if(!file)return out({ok:false,error:'ไม่พบไฟล์'},404);const {data,error}=await db.storage.from(BUCKET).createSignedUrl(file.storage_path,3600,{download:file.original_name});if(error)throw error;await audit(ctx,'download_url_created','media_file',id,{},file.project_id,id);return out({ok:true,url:data.signedUrl});}
 if(action==='projects-list'){let q=db.from('mms_projects').select('*').order('updated_at',{ascending:false}).limit(200);q=owned(q,ctx);const {data,error}=await q;if(error)throw error;return out({ok:true,projects:data||[]});}
 if(action==='project-create'){const title=String(body.title||'').trim().slice(0,200);if(!title)return out({ok:false,error:'กรุณาระบุชื่อโปรเจกต์'},400);const type=['video','cctv','audio','document','mixed'].includes(String(body.project_type))?String(body.project_type):'mixed';const {data,error}=await db.from('mms_projects').insert({owner_id:ctx.user.id,title,project_type:type,settings:body.settings&&typeof body.settings==='object'?body.settings:{}}).select().single();if(error)throw error;await audit(ctx,'project_created','project',data.id,{title,type},data.id);return out({ok:true,project:data});}
 if(action==='project-autosave'){const id=String(body.id||'');let q=db.from('mms_projects').select('*').eq('id',id);q=owned(q,ctx);const {data:p}=await q.maybeSingle();if(!p)return out({ok:false,error:'ไม่พบโปรเจกต์'},404);const settings=body.snapshot&&typeof body.snapshot==='object'?body.snapshot:{};const {data,error}=await db.from('mms_projects').update({settings,autosave_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;return out({ok:true,project:data});}
 if(action==='project-save-version'){const id=String(body.id||'');let q=db.from('mms_projects').select('*').eq('id',id);q=owned(q,ctx);const {data:p}=await q.maybeSingle();if(!p)return out({ok:false,error:'ไม่พบโปรเจกต์'},404);const next=(Number(p.current_version)||0)+1;const snapshot=body.snapshot&&typeof body.snapshot==='object'?body.snapshot:p.settings||{};const {data:v,error}=await db.from('mms_project_versions').insert({project_id:id,version_no:next,snapshot,note:String(body.note||'').slice(0,500),created_by:ctx.user.id}).select().single();if(error)throw error;await db.from('mms_projects').update({current_version:next,settings:snapshot,updated_at:new Date().toISOString()}).eq('id',id);await audit(ctx,'project_version_saved','project',id,{version:next},id);return out({ok:true,version:v});}
 if(action==='project-versions'){const id=String(body.id||'');let q=db.from('mms_projects').select('id,owner_id').eq('id',id);q=owned(q,ctx);const {data:p}=await q.maybeSingle();if(!p)return out({ok:false,error:'ไม่พบโปรเจกต์'},404);const {data,error}=await db.from('mms_project_versions').select('*').eq('project_id',id).order('version_no',{ascending:false});if(error)throw error;return out({ok:true,versions:data||[]});}
 if(action==='jobs-list'){const status=body.status?String(body.status):'';const limit=Math.min(Math.max(Number(body.limit)||60,1),100);let jobsQuery=db.from('mms_processing_jobs').select('id,job_type,module,status,progress,attempts,max_attempts,error_message,created_at,updated_at,started_at,next_retry_at,output').order('created_at',{ascending:false}).limit(limit+1);jobsQuery=owned(jobsQuery,ctx);if(status)jobsQuery=jobsQuery.eq('status',status);const cutoff=new Date(Date.now()-120000).toISOString();let queuedQuery=owned(db.from('mms_processing_jobs').select('*',{count:'exact',head:true}).eq('status','queued'),ctx);let processingQuery=owned(db.from('mms_processing_jobs').select('*',{count:'exact',head:true}).eq('status','processing'),ctx);let failedQuery=owned(db.from('mms_processing_jobs').select('*',{count:'exact',head:true}).eq('status','failed'),ctx);const [jobsResult,workersResult,queuedResult,processingResult,failedResult]=await Promise.all([jobsQuery,db.from('mms_worker_nodes').select('worker_id,worker_type,status,version,last_seen_at,capabilities,current_job_id').gte('last_seen_at',cutoff).order('last_seen_at',{ascending:false}).limit(20),queuedQuery,processingQuery,failedQuery]);if(jobsResult.error||workersResult.error||queuedResult.error||processingResult.error||failedResult.error)throw jobsResult.error||workersResult.error||queuedResult.error||processingResult.error||failedResult.error;const jobs=jobsResult.data||[];const hasMore=jobs.length>limit;if(hasMore)jobs.pop();return out({ok:true,jobs,workers:workersResult.data||[],has_more:hasMore,summary:{queued:queuedResult.count||0,processing:processingResult.count||0,failed:failedResult.count||0}});}
 if(action==='job-cancel'){const id=String(body.id||'');let q=db.from('mms_processing_jobs').select('*').eq('id',id);q=owned(q,ctx);const {data:j}=await q.maybeSingle();if(!j)return out({ok:false,error:'ไม่พบงาน'},404);if(['completed','failed','cancelled'].includes(j.status))return out({ok:false,error:'งานนี้สิ้นสุดแล้ว'},409);const {data,error}=await db.from('mms_processing_jobs').update({status:'cancelled',updated_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;await audit(ctx,'job_cancelled','processing_job',id,{},j.project_id,j.media_file_id);return out({ok:true,job:data});}
 if(action==='job-retry'){const id=String(body.id||'');let q=db.from('mms_processing_jobs').select('*').eq('id',id);q=owned(q,ctx);const {data:j}=await q.maybeSingle();if(!j)return out({ok:false,error:'ไม่พบงาน'},404);if(!['failed','cancelled'].includes(j.status))return out({ok:false,error:'Retry ได้เฉพาะงาน failed/cancelled'},409);const {data,error}=await db.from('mms_processing_jobs').update({status:'queued',progress:0,attempts:0,error_message:null,worker_id:null,locked_at:null,next_retry_at:null,started_at:null,completed_at:null,output:{},updated_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;return out({ok:true,job:data});}
 if(action==='cctv-events'){let q=db.from('mms_cctv_events').select('*,mms_cctv_sources(name,location,zone)').order('created_at',{ascending:false}).limit(Math.min(Number(body.limit)||100,300));if(body.review_status)q=q.eq('review_status',String(body.review_status));if(ctx.user.role!=='admin'){const {data:ownedMedia}=await db.from('media_files').select('id').eq('owner_id',ctx.user.id);const ids=(ownedMedia||[]).map((x:any)=>x.id);q=ids.length?q.in('media_file_id',ids):q.eq('media_file_id','00000000-0000-0000-0000-000000000000')}const {data,error}=await q;if(error)throw error;return out({ok:true,events:data||[]});}
 if(action==='cctv-review'){const id=String(body.id||'');const status=['confirmed','rejected','corrected'].includes(String(body.review_status))?String(body.review_status):'';if(!status)return out({ok:false,error:'สถานะไม่ถูกต้อง'},400);let q=db.from('mms_cctv_events').select('*').eq('id',id);if(ctx.user.role!=='admin'){const {data:ownedMedia}=await db.from('media_files').select('id').eq('owner_id',ctx.user.id);const ids=(ownedMedia||[]).map((x:any)=>x.id);q=ids.length?q.in('media_file_id',ids):q.eq('media_file_id','00000000-0000-0000-0000-000000000000')}const {data:e}=await q.maybeSingle();if(!e)return out({ok:false,error:'ไม่พบเหตุการณ์'},404);const correction=body.correction&&typeof body.correction==='object'?body.correction:{};const {data,error}=await db.from('mms_cctv_events').update({review_status:status,reviewed_by:ctx.user.id,reviewed_at:new Date().toISOString(),correction}).eq('id',id).select().single();if(error)throw error;await audit(ctx,'cctv_event_reviewed','cctv_event',id,{status,correction},e.project_id,e.media_file_id);return out({ok:true,event:data});}
 if(action==='ai-findings'){let q=db.from('mms_ai_findings').select('*').order('created_at',{ascending:false}).limit(Math.min(Number(body.limit)||100,300));if(body.module)q=q.eq('module',String(body.module));if(body.review_status)q=q.eq('review_status',String(body.review_status));if(ctx.user.role!=='admin'){const {data:ownedMedia}=await db.from('media_files').select('id').eq('owner_id',ctx.user.id);const ids=(ownedMedia||[]).map((x:any)=>x.id);q=ids.length?q.in('media_file_id',ids):q.eq('media_file_id','00000000-0000-0000-0000-000000000000')}const {data,error}=await q;if(error)throw error;return out({ok:true,findings:data||[]});}
 if(action==='ai-review'){const id=String(body.id||'');const status=['confirmed','rejected','corrected'].includes(String(body.review_status))?String(body.review_status):'';if(!status)return out({ok:false,error:'สถานะไม่ถูกต้อง'},400);let q=db.from('mms_ai_findings').select('*').eq('id',id);if(ctx.user.role!=='admin'){const {data:ownedMedia}=await db.from('media_files').select('id').eq('owner_id',ctx.user.id);const ids=(ownedMedia||[]).map((x:any)=>x.id);q=ids.length?q.in('media_file_id',ids):q.eq('media_file_id','00000000-0000-0000-0000-000000000000')}const {data:f}=await q.maybeSingle();if(!f)return out({ok:false,error:'ไม่พบผล AI'},404);const correction=body.correction&&typeof body.correction==='object'?body.correction:{};const {data,error}=await db.from('mms_ai_findings').update({review_status:status,reviewed_by:ctx.user.id,reviewed_at:new Date().toISOString(),correction}).eq('id',id).select().single();if(error)throw error;await audit(ctx,'ai_finding_reviewed','ai_finding',id,{status,correction},f.project_id,f.media_file_id);return out({ok:true,finding:data});}
 if(action==='forensic-set-hold'){if(ctx.user.role!=='admin')return out({ok:false,error:'ต้องเป็น Admin'},403);const id=String(body.id||'');const hold=!!body.legal_hold;const {data,error}=await db.from('media_files').update({legal_hold:hold,updated_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;await audit(ctx,hold?'legal_hold_enabled':'legal_hold_disabled','media_file',id,{legal_hold:hold},data.project_id,id);return out({ok:true,file:data});}
 return out({ok:false,error:'Unknown action'},400);
}catch(e){const msg=e instanceof Error?e.message:String(e);console.error(e);if(msg==='UNAUTHORIZED')return out({ok:false,error:'กรุณาเข้าสู่ระบบใหม่'},401);return out({ok:false,error:'เกิดข้อผิดพลาดของระบบ',detail:msg},500)}});
