-- MMs Pro requirements 3-8: Media Library, Background Jobs, Proxy, Projects/Versions, CCTV Forensic, AI Human Review
insert into storage.buckets(id,name,public) values('mms-media','mms-media',false) on conflict(id) do nothing;

alter table public.media_files add column if not exists project_id uuid,add column if not exists upload_status text not null default 'pending',add column if not exists source_kind text not null default 'upload',add column if not exists duration_ms bigint,add column if not exists width integer,add column if not exists height integer,add column if not exists fps numeric,add column if not exists codec text,add column if not exists audio_codec text,add column if not exists timezone text,add column if not exists metadata jsonb not null default '{}'::jsonb,add column if not exists checksum_verified boolean not null default false,add column if not exists legal_hold boolean not null default false,add column if not exists retention_until timestamptz,add column if not exists updated_at timestamptz not null default now();

create table if not exists public.mms_projects(id uuid primary key default gen_random_uuid(),owner_id uuid references public.mms_users(id) on delete set null,title text not null,project_type text not null default 'mixed' check(project_type in('video','cctv','audio','document','mixed')),status text not null default 'active' check(status in('active','archived','completed')),current_version integer not null default 0,autosave_at timestamptz,settings jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.mms_project_versions(id uuid primary key default gen_random_uuid(),project_id uuid not null references public.mms_projects(id) on delete cascade,version_no integer not null,snapshot jsonb not null default '{}'::jsonb,note text,created_by uuid references public.mms_users(id) on delete set null,created_at timestamptz not null default now(),unique(project_id,version_no));
create table if not exists public.mms_media_variants(id uuid primary key default gen_random_uuid(),media_file_id uuid not null references public.media_files(id) on delete cascade,variant_type text not null check(variant_type in('original','proxy','thumbnail','waveform','output')),storage_path text not null,mime_type text,size_bytes bigint,width integer,height integer,duration_ms bigint,checksum text,status text not null default 'ready' check(status in('pending','processing','ready','failed')),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create unique index if not exists uq_mms_media_variants_type on public.mms_media_variants(media_file_id,variant_type);

create table if not exists public.mms_processing_jobs(id uuid primary key default gen_random_uuid(),owner_id uuid references public.mms_users(id) on delete set null,project_id uuid references public.mms_projects(id) on delete set null,media_file_id uuid references public.media_files(id) on delete set null,module text not null check(module in('video','cctv','audio','document','system')),job_type text not null,status text not null default 'queued' check(status in('draft','queued','processing','completed','failed','cancelled')),progress integer not null default 0 check(progress between 0 and 100),priority integer not null default 100,attempts integer not null default 0,max_attempts integer not null default 3,input jsonb not null default '{}'::jsonb,output jsonb not null default '{}'::jsonb,idempotency_key text,worker_id text,locked_at timestamptz,next_retry_at timestamptz,error_message text,created_at timestamptz not null default now(),started_at timestamptz,completed_at timestamptz,updated_at timestamptz not null default now());
create unique index if not exists uq_mms_processing_jobs_idempotency on public.mms_processing_jobs(idempotency_key) where idempotency_key is not null;
create index if not exists idx_mms_processing_jobs_queue on public.mms_processing_jobs(status,priority,created_at);
create index if not exists idx_mms_processing_jobs_owner on public.mms_processing_jobs(owner_id,created_at desc);
create table if not exists public.mms_worker_nodes(worker_id text primary key,worker_type text not null default 'media',status text not null default 'offline' check(status in('online','busy','offline','error')),capabilities jsonb not null default '{}'::jsonb,current_job_id uuid references public.mms_processing_jobs(id) on delete set null,version text,last_seen_at timestamptz not null default now(),metadata jsonb not null default '{}'::jsonb);

create table if not exists public.mms_cctv_sources(id uuid primary key default gen_random_uuid(),owner_id uuid references public.mms_users(id) on delete set null,name text not null,location text,zone text,timezone text not null default 'Asia/Bangkok',source_type text not null default 'file' check(source_type in('file','nvr','dvr','onvif','stream')),source_ref text,active boolean not null default true,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.mms_cctv_events(id uuid primary key default gen_random_uuid(),project_id uuid references public.mms_projects(id) on delete set null,media_file_id uuid references public.media_files(id) on delete cascade,camera_id uuid references public.mms_cctv_sources(id) on delete set null,event_type text not null,title text,detail text,start_ms bigint,end_ms bigint,pre_roll_ms integer not null default 3000,post_roll_ms integer not null default 5000,confidence numeric,model_name text,model_version text,review_status text not null default 'pending' check(review_status in('pending','confirmed','rejected','corrected')),reviewed_by uuid references public.mms_users(id) on delete set null,reviewed_at timestamptz,correction jsonb not null default '{}'::jsonb,thumbnail_path text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists idx_mms_cctv_events_time on public.mms_cctv_events(created_at desc);create index if not exists idx_mms_cctv_events_media on public.mms_cctv_events(media_file_id,start_ms);

create table if not exists public.mms_ai_findings(id uuid primary key default gen_random_uuid(),project_id uuid references public.mms_projects(id) on delete set null,media_file_id uuid references public.media_files(id) on delete cascade,module text not null check(module in('video','cctv','audio','document')),finding_type text not null,title text,detail text,position_text text,start_ms bigint,end_ms bigint,confidence numeric,model_name text,model_version text,review_status text not null default 'pending' check(review_status in('pending','confirmed','rejected','corrected')),reviewed_by uuid references public.mms_users(id) on delete set null,reviewed_at timestamptz,correction jsonb not null default '{}'::jsonb,payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists idx_mms_ai_findings_review on public.mms_ai_findings(module,review_status,created_at desc);
create table if not exists public.mms_audit_events(id bigint generated always as identity primary key,actor_id uuid references public.mms_users(id) on delete set null,action text not null,entity_type text not null,entity_id text,project_id uuid references public.mms_projects(id) on delete set null,media_file_id uuid references public.media_files(id) on delete set null,detail jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists idx_mms_audit_entity on public.mms_audit_events(entity_type,entity_id,created_at desc);create index if not exists idx_mms_audit_media on public.mms_audit_events(media_file_id,created_at desc);

alter table public.media_files drop constraint if exists media_files_project_id_fkey;alter table public.media_files add constraint media_files_project_id_fkey foreign key(project_id) references public.mms_projects(id) on delete set null;
create index if not exists idx_media_files_owner_created on public.media_files(owner_id,created_at desc);create index if not exists idx_media_files_project on public.media_files(project_id,created_at desc);

alter table public.mms_projects enable row level security;alter table public.mms_project_versions enable row level security;alter table public.mms_media_variants enable row level security;alter table public.mms_processing_jobs enable row level security;alter table public.mms_worker_nodes enable row level security;alter table public.mms_cctv_sources enable row level security;alter table public.mms_cctv_events enable row level security;alter table public.mms_ai_findings enable row level security;alter table public.mms_audit_events enable row level security;
revoke all on public.mms_projects,public.mms_project_versions,public.mms_media_variants,public.mms_processing_jobs,public.mms_worker_nodes,public.mms_cctv_sources,public.mms_cctv_events,public.mms_ai_findings,public.mms_audit_events from anon,authenticated;
grant select,insert,update,delete on public.mms_projects,public.mms_project_versions,public.mms_media_variants,public.mms_processing_jobs,public.mms_worker_nodes,public.mms_cctv_sources,public.mms_cctv_events,public.mms_ai_findings,public.mms_audit_events to service_role;

create or replace function public.mms_claim_processing_job(p_worker_id text,p_job_types text[]) returns jsonb language plpgsql security definer set search_path=public,pg_catalog as $$declare r public.mms_processing_jobs;begin with picked as(select id from public.mms_processing_jobs where status='queued' and job_type=any(p_job_types) and(next_retry_at is null or next_retry_at<=now()) order by priority,created_at for update skip locked limit 1) update public.mms_processing_jobs j set status='processing',worker_id=p_worker_id,locked_at=now(),started_at=coalesce(started_at,now()),attempts=attempts+1,updated_at=now() from picked where j.id=picked.id returning j.* into r;if r.id is null then return null;end if;insert into public.mms_worker_nodes(worker_id,worker_type,status,current_job_id,last_seen_at) values(p_worker_id,'media','busy',r.id,now()) on conflict(worker_id) do update set status='busy',current_job_id=excluded.current_job_id,last_seen_at=now();return to_jsonb(r);end$$;
revoke all on function public.mms_claim_processing_job(text,text[]) from public,anon,authenticated;grant execute on function public.mms_claim_processing_job(text,text[]) to service_role;

create or replace function public.mms_queue_checksum_after_ready() returns trigger language plpgsql security definer set search_path=public,pg_catalog as $$begin if new.upload_status='ready' and(old.upload_status is distinct from new.upload_status) and new.sha256 is null then insert into public.mms_processing_jobs(owner_id,project_id,media_file_id,module,job_type,status,input,idempotency_key) values(new.owner_id,new.project_id,new.id,case when new.source_kind='cctv' then 'cctv' else case when new.media_type in('video','audio','document') then new.media_type else 'system' end end,'checksum_compute','queued',jsonb_build_object('source_path',new.storage_path),'checksum:'||new.id) on conflict(idempotency_key) where idempotency_key is not null do nothing;end if;return new;end$$;
revoke all on function public.mms_queue_checksum_after_ready() from public,anon,authenticated;drop trigger if exists trg_mms_queue_checksum_after_ready on public.media_files;create trigger trg_mms_queue_checksum_after_ready after update of upload_status on public.media_files for each row execute function public.mms_queue_checksum_after_ready();
